# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tickets_pb2 as tickets__pb2

GRPC_GENERATED_VERSION = '1.63.0'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tickets_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class TicketServiceStub(object):
    """Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddTicket = channel.unary_unary(
                '/TicketService/AddTicket',
                request_serializer=tickets__pb2.Ticket.SerializeToString,
                response_deserializer=tickets__pb2.Ticket.FromString,
                _registered_method=True)
        self.GetAllTickets = channel.unary_unary(
                '/TicketService/GetAllTickets',
                request_serializer=tickets__pb2.Empty.SerializeToString,
                response_deserializer=tickets__pb2.TicketList.FromString,
                _registered_method=True)
        self.GetTicket = channel.unary_unary(
                '/TicketService/GetTicket',
                request_serializer=tickets__pb2.TicketId.SerializeToString,
                response_deserializer=tickets__pb2.Ticket.FromString,
                _registered_method=True)
        self.UpdateTicket = channel.unary_unary(
                '/TicketService/UpdateTicket',
                request_serializer=tickets__pb2.Ticket.SerializeToString,
                response_deserializer=tickets__pb2.Ticket.FromString,
                _registered_method=True)
        self.DeleteTicket = channel.unary_unary(
                '/TicketService/DeleteTicket',
                request_serializer=tickets__pb2.TicketId.SerializeToString,
                response_deserializer=tickets__pb2.Empty.FromString,
                _registered_method=True)


class TicketServiceServicer(object):
    """Service
    """

    def AddTicket(self, request, context):
        """Create
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAllTickets(self, request, context):
        """Read 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTicket(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTicket(self, request, context):
        """Update
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTicket(self, request, context):
        """Delete
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicketServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTicket,
                    request_deserializer=tickets__pb2.Ticket.FromString,
                    response_serializer=tickets__pb2.Ticket.SerializeToString,
            ),
            'GetAllTickets': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAllTickets,
                    request_deserializer=tickets__pb2.Empty.FromString,
                    response_serializer=tickets__pb2.TicketList.SerializeToString,
            ),
            'GetTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTicket,
                    request_deserializer=tickets__pb2.TicketId.FromString,
                    response_serializer=tickets__pb2.Ticket.SerializeToString,
            ),
            'UpdateTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateTicket,
                    request_deserializer=tickets__pb2.Ticket.FromString,
                    response_serializer=tickets__pb2.Ticket.SerializeToString,
            ),
            'DeleteTicket': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteTicket,
                    request_deserializer=tickets__pb2.TicketId.FromString,
                    response_serializer=tickets__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TicketService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicketService(object):
    """Service
    """

    @staticmethod
    def AddTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/AddTicket',
            tickets__pb2.Ticket.SerializeToString,
            tickets__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAllTickets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/GetAllTickets',
            tickets__pb2.Empty.SerializeToString,
            tickets__pb2.TicketList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/GetTicket',
            tickets__pb2.TicketId.SerializeToString,
            tickets__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/UpdateTicket',
            tickets__pb2.Ticket.SerializeToString,
            tickets__pb2.Ticket.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteTicket(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/TicketService/DeleteTicket',
            tickets__pb2.TicketId.SerializeToString,
            tickets__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
