# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tickets.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rtickets.proto\"]\n\x06Ticket\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65vent\x18\x03 \x01(\t\x12\r\n\x05venue\x18\x04 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x05 \x01(\t\x12\r\n\x05price\x18\x06 \x01(\x03\"&\n\nTicketList\x12\x18\n\x07tickets\x18\x01 \x03(\x0b\x32\x07.Ticket\"\x16\n\x08TicketId\x12\n\n\x02id\x18\x01 \x01(\t\"\x07\n\x05\x45mpty2\xc4\x01\n\rTicketService\x12\x1f\n\tAddTicket\x12\x07.Ticket\x1a\x07.Ticket\"\x00\x12&\n\rGetAllTickets\x12\x06.Empty\x1a\x0b.TicketList\"\x00\x12!\n\tGetTicket\x12\t.TicketId\x1a\x07.Ticket\"\x00\x12\"\n\x0cUpdateTicket\x12\x07.Ticket\x1a\x07.Ticket\"\x00\x12#\n\x0c\x44\x65leteTicket\x12\t.TicketId\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tickets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TICKET']._serialized_start=17
  _globals['_TICKET']._serialized_end=110
  _globals['_TICKETLIST']._serialized_start=112
  _globals['_TICKETLIST']._serialized_end=150
  _globals['_TICKETID']._serialized_start=152
  _globals['_TICKETID']._serialized_end=174
  _globals['_EMPTY']._serialized_start=176
  _globals['_EMPTY']._serialized_end=183
  _globals['_TICKETSERVICE']._serialized_start=186
  _globals['_TICKETSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
